# Generated by Django 4.2 on 2026-03-08 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePonedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_gallinas', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('cantidad_muerto', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=0)),
                ('edad_semanas', models.IntegerField(default=0)),
                ('muertos_semanales', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_ponedoras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPesoPonedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lotes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loteponedora')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_huevos', models.IntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loteponedora')),
            ],
            options={
                'db_table': 'registro_huevos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InsumosPonedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Alimento', 'Alimento'), ('Medicamento', 'Medicamento'), ('Vacuna', 'Vacuna'), ('Vitamina', 'Vitamina'), ('Desinfectante', 'Desinfectante'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('fecha', models.DateField()),
                ('lotes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loteponedora')),
            ],
        ),
    ]
